name: CI/CD para Frontend con Seguridad

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a la rama principal
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Gitleaks
        run: |
          curl -sSL https://github.com/zricethez/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Ejecutar Gitleaks para detectar credenciales
        run: gitleaks detect --verbose --redact --source . || true  # No falla el pipeline si encuentra credenciales

  testCalidadUnitaria:
    runs-on: ubuntu-latest
    needs: gitleaks  # Se ejecuta después de gitleaks
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: |
          echo "Instalando dependencias de Next.js..."
          sleep 10  # Simulación
          echo "Instalación completada."

      - name: Ejecutar pruebas unitarias (Simulado)
        run: |
          echo "Ejecutando pruebas unitarias..."
          sleep 30  # Simulación
          echo "Todas las pruebas pasaron exitosamente."

  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    needs: testCalidadUnitaria
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be deshabilitado para una mejor relevancia del análisis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  escaneoSeguridad:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias con pnpm
        run: pnpm install

      - name: Iniciar servidor local de Next.js
        run: |
          pnpm run dev &
          npx wait-on http://localhost:3000

      - name: Ejecutar escaneo de seguridad con OWASP ZAP
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://localhost:3000"
          fail_on_warn: true  # Cambia a false si no quieres que falle en advertencias

      - name: Subir reporte de OWASP ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: .

  lighthouse:
    runs-on: ubuntu-latest
    needs: escaneoSeguridad
    steps:
      - name: Instalar Lighthouse
        run: npm install -g lighthouse

      - name: Ejecutar análisis de rendimiento con Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: "./lighthouserc.json"
          urls: "http://localhost:3000"
          uploadArtifacts: true

      - name: Subir reporte de Lighthouse
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouseci/

  deploy:
    runs-on: ubuntu-latest
    needs: lighthouse
    steps:
      - name: Simular despliegue en Vercel
        run: |
          echo "Desplegando en Vercel..."
          sleep 33  # Simulación
          echo "Despliegue exitoso."
