name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest  # Cambiado a Ubuntu porque React no necesita Windows

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para un análisis completo en SonarQube

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión recomendada de Node.js para React

      - name: Instalar dependencias
        run: npm install

      - name: Construir la aplicación de React
        run: npm run build

      - name: Ejecutar análisis de SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
