name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código fuente desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js con soporte para pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
# 3. Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Instalar dependencias con pnpm
      - name: Install dependencies
        run: pnpm install
     

      # 6. Construir la aplicación de React
      - name: Build React App
        run: pnpm run build

      # 7. Ejecutar análisis de SonarCloud
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
